/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as QrCodeRouteImport } from './routes/qr-code'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as CategoryBoardsRouteImport } from './routes/category.boards'
import { Route as CategoryLaminatesRouteImport } from './routes/category.laminates'
import { Route as CategoryPanelsRouteImport } from './routes/category.panels'
import { Route as CategoryPlywoodRouteImport } from './routes/category.plywood'
import { Route as CategoryVeneersRouteImport } from './routes/category.veneers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeRoute = QrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryBoardsRoute = CategoryBoardsRouteImport.update({
  id: '/category/boards',
  path: '/category/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryLaminatesRoute = CategoryLaminatesRouteImport.update({
  id: '/category/laminates',
  path: '/category/laminates',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryPanelsRoute = CategoryPanelsRouteImport.update({
  id: '/category/panels',
  path: '/category/panels',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryPlywoodRoute = CategoryPlywoodRouteImport.update({
  id: '/category/plywood',
  path: '/category/plywood',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryVeneersRoute = CategoryVeneersRouteImport.update({
  id: '/category/veneers',
  path: '/category/veneers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr-code': typeof QrCodeRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/category/boards': typeof CategoryBoardsRoute
  '/category/laminates': typeof CategoryLaminatesRoute
  '/category/panels': typeof CategoryPanelsRoute
  '/category/plywood': typeof CategoryPlywoodRoute
  '/category/veneers': typeof CategoryVeneersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr-code': typeof QrCodeRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/category/boards': typeof CategoryBoardsRoute
  '/category/laminates': typeof CategoryLaminatesRoute
  '/category/panels': typeof CategoryPanelsRoute
  '/category/plywood': typeof CategoryPlywoodRoute
  '/category/veneers': typeof CategoryVeneersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr-code': typeof QrCodeRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/category/boards': typeof CategoryBoardsRoute
  '/category/laminates': typeof CategoryLaminatesRoute
  '/category/panels': typeof CategoryPanelsRoute
  '/category/plywood': typeof CategoryPlywoodRoute
  '/category/veneers': typeof CategoryVeneersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/qr-code'
    | '/terms-of-service'
    | '/category/boards'
    | '/category/laminates'
    | '/category/panels'
    | '/category/plywood'
    | '/category/veneers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/qr-code'
    | '/terms-of-service'
    | '/category/boards'
    | '/category/laminates'
    | '/category/panels'
    | '/category/plywood'
    | '/category/veneers'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/qr-code'
    | '/terms-of-service'
    | '/category/boards'
    | '/category/laminates'
    | '/category/panels'
    | '/category/plywood'
    | '/category/veneers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QrCodeRoute: typeof QrCodeRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  CategoryBoardsRoute: typeof CategoryBoardsRoute
  CategoryLaminatesRoute: typeof CategoryLaminatesRoute
  CategoryPanelsRoute: typeof CategoryPanelsRoute
  CategoryPlywoodRoute: typeof CategoryPlywoodRoute
  CategoryVeneersRoute: typeof CategoryVeneersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code': {
      id: '/qr-code'
      path: '/qr-code'
      fullPath: '/qr-code'
      preLoaderRoute: typeof QrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/boards': {
      id: '/category/boards'
      path: '/category/boards'
      fullPath: '/category/boards'
      preLoaderRoute: typeof CategoryBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/laminates': {
      id: '/category/laminates'
      path: '/category/laminates'
      fullPath: '/category/laminates'
      preLoaderRoute: typeof CategoryLaminatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/panels': {
      id: '/category/panels'
      path: '/category/panels'
      fullPath: '/category/panels'
      preLoaderRoute: typeof CategoryPanelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/plywood': {
      id: '/category/plywood'
      path: '/category/plywood'
      fullPath: '/category/plywood'
      preLoaderRoute: typeof CategoryPlywoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/veneers': {
      id: '/category/veneers'
      path: '/category/veneers'
      fullPath: '/category/veneers'
      preLoaderRoute: typeof CategoryVeneersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QrCodeRoute: QrCodeRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  CategoryBoardsRoute: CategoryBoardsRoute,
  CategoryLaminatesRoute: CategoryLaminatesRoute,
  CategoryPanelsRoute: CategoryPanelsRoute,
  CategoryPlywoodRoute: CategoryPlywoodRoute,
  CategoryVeneersRoute: CategoryVeneersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
